sudo: required
dist: trusty

language: python

python:
  - "3.5"

cache:
  apt: true

addons:
  apt:
    packages:
      - cmake
      - g++-5
    sources:
      - ubuntu-toolchain-r-test

install:
  - wget https://github.com/catchorg/Catch2/releases/download/v2.4.1/catch.hpp -P symbsat-cpp/tests
  - pip install -U pip setuptools
  - pip install flake8
  - pip install coverage
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - (cd symbsat-py && coverage run --branch -m unittest tests/test_*.py)
  - (mkdir build && cd build && cmake ../symbsat-cpp && make -j2 && tests/unittests)

after_success:
  - (cd symbsat-cpp && bash <(curl -s https://codecov.io/bash))
